# Site wide configuration

title: Timposu Labs
description: Kompulan tutorial pemrograman, linux server dan ilmu komputer lainnya
logo: logo-timposu.png # 120x120 px default image used for Twitter summary card
teaser: photo-1441015401724-70d16b783f5c.jpg # 400x250 px default teaser image used in image archive grid
locale: id
url:

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge
gems:
  - jekyll-sitemap
  - jekyll-gist


# Octopress configuration

# Default extensions
post_ext: md
page_ext: md

# Found in _templates/
post_layout: article
page_layout: article

# Format titles with titlecase?
titlecase: true

# Site owner
owner:
  name: Ucup Timposu
  web: http://timposu.com
  email: ucup.timposu@gmail.com
  twitter: ucuptimposu
  bio: "Founder dan Admin  <a href='http://timposu.com'>Timposu.com</a>"
  avatar: bio-ucup.png # 160x160 px image for author byline
  google:
    ad-client: ca-pub-4504493660273886
    ad-slot: 7129625873
  disqus-shortname: timposu

exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
